# Main navigation.
nav:
  - Introduction: index.md
  - Team: team.md
  - Funding: funding.md
  - Credits: credits.md
  - License: license.md
  - Contact: contact.md
  - Getting Started:
    - Introduction: getting-started/index.md
    - Docker Compose: getting-started/docker-compose.md
    - Docker: getting-started/docker.md
    - Raspberry Pi: getting-started/raspberry-pi.md
    - Demo Image: getting-started/demo.md
    - Kubernetes: getting-started/kubernetes.md
    - Scalability: getting-started/scalability.md
    - Updates: getting-started/updates.md
    - Caching: getting-started/caching.md
    - Support: getting-started/support.md
    - FAQ: getting-started/faq.md
  - User Guide:
    - Introduction: user-guide/index.md
    # - Setting up: user-guide/setup.md
    - Navigate: user-guide/navigate.md
    - Files & Folders:
      - Import vs Index: user-guide/library/import-vs-index.md
      - Import: user-guide/library/import.md
      - Index: user-guide/library/indexing.md
      - Upload via Web UI: user-guide/library/upload.md
      - WebDAV Upload: user-guide/library/webdav.md
      - Files: user-guide/library/files.md
      #- Import from camera: user-guide.md
      #- Import from Flickr: user-guide.md
      #- Import from Facebook: user-guide.md
      #- Import from NAS: user-guide.md
      #- Import from Google Photos: user-guide.md
      #- Import from Apple Photos: user-guide.md
      #- Import from One Drive: user-guide.md
    # - Sync and Back Up:
    # - WebDAV Sync
    #    - Nextcloud: user-guide/nextcloud.md
    - Organize:
      - Browse: user-guide/organize/browse.md
      - Review: user-guide/organize/review.md
      - Private: user-guide/organize/private.md
      - Archive: user-guide/organize/archive.md
      - Albums: user-guide/organize/albums.md
      - Folders: user-guide/organize/folders.md
      - Labels: user-guide/organize/labels.md
      - Places: user-guide/organize/places.md
      - Videos: user-guide/organize/video.md
      - Moments: user-guide/organize/moments.md
      - Calendar: user-guide/organize/calendar.md
      - Download photos: user-guide/organize/download.md
      - Edit photos: user-guide/organize/edit.md
    # - Sharing: user-guide/share.md
    - Settings:
      - Library: user-guide/settings/library.md
      - User Interface: user-guide/settings/ui.md
      - Places: user-guide/settings/places.md
      - Thumbnails: user-guide/settings/thumbnails.md
    # - Metadata: user-guide/metadata.md
  - Developer Guide:
    - Introduction: developer-guide/index.md
    - Setup: developer-guide/setup.md
    - Directories: developer-guide/directories.md
    - Configuration: developer-guide/configuration.md
    - Tests: developer-guide/tests.md
    - Issues: developer-guide/issues.md
    - Pull Requests: developer-guide/pull-requests.md
    - Code Quality: developer-guide/code-quality.md
    - Documentation: developer-guide/documentation.md
    #- FAQ:
    #    - General Questions: faq/index.md
    #- Developer: faq/developer-faq.md
    #- User: faq/user-faq.md
    #- Enterprise: faq/enterprise-faq.md

# External links.
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/photoprism
    - icon: fontawesome/brands/paypal
      link: https://www.paypal.me/photoprism
    - icon: material/chat
      link: https://gitter.im/browseyourlife/community
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/browseyourlife
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/photoprism/
    - icon: material/home
      link: https://photoprism.org/

# Project paths.
docs_dir: docs
site_dir: site

# Project information.
site_name: PhotoPrism
site_description: User Guide
site_author: PhotoPrism.org
site_url: https://docs.photoprism.org/

# Repository information.
repo_name: photoprism/photoprism
repo_url: https://github.com/photoprism/photoprism
edit_uri: ""
copyright: 'Made with ❤ in Berlin'

# Theme configuration.
theme:
  name: 'material'
  custom_dir: overrides

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs
    #- instant
  palette:
    scheme: default
    primary: white
    accent: amber
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo
  favicon: img/favicon.png

plugins:
  - search

# MkDocs extensions.
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
